### ISSUE TITLE
Unsafe ServiceProvider.available() method

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#114]
Method `ServiceProvider.available()` is currently implemented as below, where `getProviders()` returns a reference to an internal array (not a copy):

```
  public static List<ServiceProvider> available() {
    return Arrays.asList(getProviders());
  }
```

But `Arrays.asList` returns a modifiable list; users can perform `List.set(int, ServiceProvider)` operations, thus modifying the internal array. Two different fixes are possible, depending if JSR 385 targets JDK 8 or JDK 9. What is the target JDK version?

Needs #113 (mainly for project structure)
Needs #137

**Comment by keilw** [comment]
The API must still run under Java SE 8 while module-info is included, but the JAR should not be restricted to Java SE 9 or above. I believe the majority of real users won't jump on Java 9, 10 or 11 just because Oracle now pushes them out faster. We could also increase the version cycle and do a 2.0.1 or 2.1 release of the API either as "Fix Pack" (like JSR 354) or an official MR (probably not required if the API doesn't change on the outside) for Java 9 or 10 as the minimal version, but right now, take all the other JSRs like CDI 2, Bean Validation 2, etc. none of them requires Java 9 so we shouldn't either.

**Comment by desruisseaux** [comment]
How do we manage multi-version JAR file for this project, if we want to provide two different classes depending if running on Java 8 or Java 9? Another different between the two platforms is in the use of loggers.

**Comment by keilw** [comment]
I am not sure, if we should open that "box". First and foremost multi-version JARs double the size of the JAR because literally everything, not just the delta gets squeezed into them. I tried it before @atsticks' approach with the correct set of Maven build steps helped create a Java 8 compatible JAR with Java 9 Jigsaw module-info.

**Comment by keilw** [comment]
Does it work in Maven? I tried some approaches to multi-jar Gunnar, the BV Spec Lead mentioned. Maybe there are other plugins by now, the overhead of switching to say Gradle (just because it's "cooler") would be too painful, so if there's a reasonable Maven build chain to do it, give it a try. However, what is the major problem with the Java SE8 mechanism? Does it have a performance penalty or some other problem only doing this Java9+ can solve?

**Comment by desruisseaux** [comment]
I did not tried yet, but I think it should work. We can use the `maven-antrun-plugin` plugin until a more official plugin become available (if this happen). We can take this opportunity for fixing #113 in same time.

In Java 9, we can use `List.of(...)` instead of `Arrays.asList(…)`. The former is unmodifiable, contrarily to the later. This avoid the need to wrap in `Collections.unmodifiableList(...)`, thus saving an indirection level.

Another thing is that the Java 9 profile could use `System.Logger` for avoiding direct dependency to the `java.util.logging` module.

**Comment by keilw** [comment]
It is usually a tiny list with very few entries, so even if Collections.unmodifiableLists() had any performance penalty, this is not a list with millions of entries, so please let's stick to Java 8 for now. 
Take the [Jakarta EE Survey](https://jakarta.ee/documents/insights/2018-jakarta-ee-developer-survey.pdf) as a recent example with nearly 90% stating to use Java 8 in production compared to less than 6% for Java 9. While Java 6 still used by nearly 23% and Java 7 by 45%. It seems multiple choices were possible but it is a clear sign, we'll have Java 8 for some time. This small place does not justify a multi-version JAR yet IMO. `java.util.logging` is also used only in this class alone. Interesting about `System.Logger`, it seems almost like a miniature version of a JSR @myfear once hoped for. Whether it really allows plugging Log4J instead of `java.util.logging` into certain modules, hard to say, but maybe it can be done at some point. 
The JAR is around `35k`, even if it would only cost 4 or 5, having this in a single class and merely 3 lines or so being different seems premature. Some elements now deprecated like `UnitFormatService` should be removed likely with the next significant release, why not wait with this till it gains us a few `kB` in another place or more crucial things like Value Objects in a new JDK make multi-version JARs almost inevitable. Please create a follow-up ticket, but let's solve this issue with Java 8 means.

**Comment by keilw** [comment]
If a multi-version JAR could only (efficiently) packaged by some archaic thing like maven-antrunner, we could investigate (in a separate ticket) but #113 is a non-issue, there are several JSRs led by Oracle like JSON-P that do it exactly the same way with `base-compile` and `compile`.

**Comment by desruisseaux** [comment]
Okay for the `Collections.unmodifiableList` cost not being a big issue.

On `java.util.logging`, the use of multi-JAR files would allow to cut the explicit dependency to that module. It is still used if the user has the `java.util.logging` module on the module-path. So this 2 kb cost (after compression in a JAR file - the 4 kb was the uncompressed class file) allows users to save 118 kb if they want. Note also that this is a cost of disk space, not memory. My understanding of previous discussion was that micro-devices was no so short in disk space; the limited resource is memory, which is not impacted by multi-JAR files.

On #113, the issue is not that the `module-info.java` file is in a different directory like `base-compile` and `base`. My issue is that the way it is done in Unit-API gives the impression that someone has confused packages with modules (i.e. wrongly believed that `module-info.java` needs to be in a package of the same name). This `java/measure/module-info.java` file is under the same `src/main/java` directory than the rest of the code. We would expect JDK 9 `javac` to be able to compile `src/main/java` content. Currently it is not possible without excluding `module-info.java`, even when compiling with JDK 9 or 10.

**Comment by keilw** [comment]
@desruisseaux Would you like to do this now, that there's a separate Java 9 codebase (but also solve it for Java 8) or should someone else pick it up?

**Comment by desruisseaux** [comment]
I will try to do it during November 1st holiday.

**Comment by desruisseaux** [comment]
The changes proposed in the pull request are the minimal ones, fixing only the `ServiceProvider.available()` mutability issue. A next pull request could be to make some methods more efficient on Java 9, by avoiding to initialize classes when not needed. I guess it would be a separated issue?

**Comment by keilw** [comment]
Can this be closed then?

**Comment by desruisseaux** [comment]
I forgot that one. Yes, #124 is exactly the continuation I had in mind. #114 can be closed then.

**Comment by keilw** [comment]
So if this has been solved and everything to improve is covered by #124 then let's close it. Of you spot something missing in #124, please either adjust it (in some cases we may also use the bullet-point sub-task feature of GitHub or create a separate new ticket.
