### ISSUE TITLE
Evaluate multi-release-jars

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#129]
At a later point (either a MR of V2 or a follow-up JSR) it could make sense to explore Java 9+ multi-release-jars. Right now there is merely a line or two internal code so it seems questionable what value it brings (e.g. a 50% faster execution time or similar) 
Value Types and Project Valhalla have not moved over the last 3 years, it seems Oracle has other priorities right now: http://openjdk.java.net/jeps/169

Other features like `var` (Java 10) in the API make no sense at all because it is only meant for local variable, not for public API methods.

Unless a future version of Java suddenly added killer features like `reified generics`, which the API could benefit a lot, there is no real use for new features in the API.

**Comment by desruisseaux** [comment]
Multi-releases JAR files is not an API feature. It is an implementation details which does not change anything to the API. It does not commit ourselves for the future in anyway; we can remove it from any future releases with no problem.

We do have an implementation in Unit API, which is the `ServiceProvider` class. This class is the sole target of multi-releases JAR at this time. The reason why multi-release JAR would be useful is because it would allow us to remove the requirement for `java.logging` module on Java 9. I do like `java.logging` myself, but I realize that other developers have different view and some of them may not appreciate that we force them to have this dependency. Multi-releases JAR file help us to avoid that.

Multi-releases JAR is already used by `jaxb-api-2.3.0.jar`, `log4j-api-2.10.0.jar`, `plexus-java-0.9.10.jar` and `junit-platform-commons-1.1.0.jar`, looking only at the files that Maven downloaded for me (my `~/.m2/repository` directory). There is probably many other artifacts using it on Maven Central. An example of major project moving to it is [Lucene](https://issues.apache.org/jira/browse/LUCENE-7966).

**Comment by keilw** [comment]
Actually `ServiceProvider` is not an implementation, it is an abstract base class. JAXB seems one of the few JSR related APIs, but https://github.com/eclipse-ee4j/jaxb-api/tree/master/jaxb-api/src/main/mr-jar/javax/xml/bind contains just one class that is used entirely for Java 9. That is not the case, in fact it does not bother using the logging abstraction ;-) Do you see concrete use case for genuine Java 9 mechanisms like `Module` in `ServiceProvider`?

**Comment by keilw** [comment]
Looks like it worked aside from 3k extra, but some of it will hopefully go away when removing deprecated elements later. Was the lower version number 1.2 of the Java 9 `ServiceProvider `on purpose?

**Comment by desruisseaux** [comment]
Hello Werner

Thanks for the merge. The lower version number (1.2) is accidental. I can submit a patch tomorrow if it helps.

Can you provide some more details about the error you get from Eclipse IDE? Do you have a stack trace? Which Java version is running?

**Comment by keilw** [comment]
I already added a `@Deprecated` annotation with the flag only in the Java 9 variant, so the versions are in sync now.  After using JDK 10.0.1 for the IDE or maybe some ad-hoc updates to JBoss Tools, it may have gone away. There was never a stack-trace, if so only in Eclipse internal logs, therefore I cannot say, it still persists, but it shows up less now in the same classes.
