### ISSUE TITLE
List of parseable units

### ISSUE THREAD

**Issue by Gillani0** [unitsofmeasurement/unit-api#159]
Hi, 

I can't seem to find the list of units that can be parsed by the AbstractUnit. The list provided here is not fully compatible:
https://github.com/unitsofmeasurement/uom-tools/blob/master/obix/src/main/resources/etc/units.txt

Thanks in advance.
Cheers

**Comment by keilw** [comment]
They are not directly related, the units provided by systems like OBIX or others would be a particular `SystemOfUnits` implementation. In [SystemOfUnits](https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/spi/SystemOfUnits.java) the `getUnits()` method offers a `Set` of all units in this system. In most cases `toString()` is the best indicator for parseable strings.

**Comment by Gillani0** [comment]
Alright, the parsing is based on the unit class instance and prefixes rather than loading from a file. It's quite clean, however, specific list of acceptable units would be quite useful. Cheers

**Comment by keilw** [comment]
It depends on the `SystemOfUnits` implementation. I am not aware of any that do it, but a particular implementation could in theory load a file. Since the units and quantities are typesafe, most implementations prefer otherwise. Eclipse UOMo has a late binding version of the UCUM system where the collection of units is dynamically built from the UCUM XML file, but in that case it is a bit less strict with quantity types or incompatible ones may only show at runtime.
