### ISSUE TITLE
Get Codacy grade to A

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#163]
The Codacy grade is currently B, it should be A.

List of Codacy suggestions to be ignored/muted:

- Use equals() to compare object references. An overall amount of **2** issues: (`src/main/java/javax/measure/spi/ServiceProvider.java`, `src/main/jdk9/javax/measure/spi/ServiceProvider.java`). 
- Method names should not start with capital letters (that was decided on #165). An overall amount of **28** issues:
 (`src/main/java/javax/measure/BinaryPrefix.java` and `src/main/java/javax/measure/MetricPrefix.java`)

**Comment by desruisseaux** [comment]
We should not follow blindly Codacy (or any other tools) diagnostic. All tools have false positives, sometime in large amount. If Codacy said that a code needs to be changed, its suggestions need to be investigated on a case-by-case basis. Many times the tools is wrong.

**Comment by keilw** [comment]
It can be configured to skip or permanently ignore what is not appropriate for our situation. E.g. the constant prefixes.

**Comment by thodorisbais** [comment]
@desruisseaux couldn't agree more, that was also my meaning [here](https://github.com/unitsofmeasurement/unit-api/pull/166#issue-246734056).

**Comment by thodorisbais** [comment]
Taking into account the discussion above, as well as the discussion at #166 , we cannot accept each and every suggestion from Codacy (due to our standards, roadmap, etc.). That said, we need to keep a list with the issues we need to manually mute/ignore at Codacy.

Initiated that list [above](https://github.com/unitsofmeasurement/unit-api/issues/163#issue-401121771).

**Comment by keilw** [comment]
The https://app.codacy.com/project/unitsofmeasurement/unit-api/dashboard shows some issues, not sure, why https://app.codacy.com/project/unitsofmeasurement/unit-api_2/dashboard is different, if it's a matter of configuration let's try to consolidate it and delete the duplicate.

**Comment by thodorisbais** [comment]
As I mentioned some time ago (in another issue or PR, I cannot recall at the moment), I have accidentally created unit-api_2 project while playing around with Codacy. However, given that I have no write rights, I think it's kinda impossible to delete it from my side. So, @keilw , I would suggest that I'm given some write rights to play a bit more, consolidate the two and delete the redundant one, so that we can move forward.

**Comment by keilw** [comment]
I'll try to delete it, thanks for explaining

**Comment by thodorisbais** [comment]
Cool, hope we figure it out soon!

**Comment by thodorisbais** [comment]
On #165 we decided to stick with prefixing method names with an uppercase letter. Hence, we should also mute related Codacy issues (an overall amount of 28 issues). [Updated this issue](https://github.com/unitsofmeasurement/unit-api/issues/163#issue-401121771).

**Comment by keilw** [comment]
Yes, that's a good idea, thanks.

**Comment by thodorisbais** [comment]
By the way, did we manage to find a way to mute/ignore issues on our codacy project?

**Comment by keilw** [comment]
Not sure, if it needs admin rights in the Codacy profile but yes, they can be ignored either per incident or for an entire file or pattern (e.g. that "must not start with uppercase")

**Comment by thodorisbais** [comment]
I think it needs; I'm currently only able to see these two projects (as I've mentioned some time ago):
![screenshot 2019-03-05 at 19 35 32](https://user-images.githubusercontent.com/5684688/53828956-53276d00-3f7f-11e9-8139-8bb7e6cefa06.png)
