### ISSUE TITLE
Allow non-double arguments for some Unit operations

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#191]
As a side-effect of https://github.com/unitsofmeasurement/indriya/issues/220 @andi-huber came across a discrepancy between `Quantity` or `UnitConverter` and `Unit` where the latter only accepts double for operations `multiply(), divide()` or `shift()`. It would mainly override existing methods to allow greater precision, e.g. using `BigDecimal`.

**Comment by andi-huber** [comment]
Yes, `Unit` does have 

- Unit<Q> divide(double divisor);
- Unit<Q> multiply(double multiplier);
- Unit<Q> shift(double offset);

but does not have 

- Unit<Q> divide(Number divisor);
- Unit<Q> multiply(Number multiplier);
- Unit<Q> shift(Number offset);

My proposal is to add these 3 methods to `Unit`.

**Comment by keilw** [comment]
@unitsofmeasurement/experts, @unitsofmeasurement/contributors does anybody see a big problem with that?

**Comment by thodorisbais** [comment]
I'm maybe a bit late here, but I guess we're talking about overloading, instead of overriding.
Anyway, the result doesn't change; that is, we still managed to maintain existing functionality and add the "more precise" functionality as well, so, I'm pretty fine with that.

Given the latest commits of Werner, I guess we're good here.
Shall we close it?

**Comment by andi-huber** [comment]
I'm happy with the latest commits, not vetoing if you want to close this one.

**Comment by thodorisbais** [comment]
Cool, closing this one then.
