### ISSUE TITLE
Use @API Guardian? 

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#202]
In a future version, if it doesn't add too much extra payload to the JAR size we may use we may use [@API Guardian](https://github.com/apiguardian-team/apiguardian) here, too.

**Comment by thodorisbais** [comment]
What is the rational behind tagging this as "deferred"?

**Comment by desruisseaux** [comment]
I can see its use in implementations, or temporarily in unit-api during development phase, but it seems a little bit surprising to declare e.g. an API as experimental in an interface published as a JCP standard. I think it may also be desirable to keep unit-api free of any runtime dependency. I would be more neutral if `API` was a build-time dependency only, but unfortunately it is declared with `@Retention(RUNTIME)` instead of `@Retention(SOURCE)`.

**Comment by keilw** [comment]
That's why it is deferred to a possible future version.
