### ISSUE TITLE
enum missing in javax.measure.MetricPrefix

### ISSUE THREAD

**Issue by sonideft** [unitsofmeasurement/unit-api#255]
In version of unit-api.jar 2.0, the sources have an enum for DEKA. In the latest source it was removed. I'm not sure why as the related static method is retained. I needed to add it back in order to get the latest version of GeoTools (Snapshot 31) to run (compiles fine). I'm not sure where the issue actually is, but I thought I would start here as DEKA appears half implemented.

**Comment by keilw** [comment]
This was discussed and deciced upon in #250, @desruisseaux also said in that ticket, it should not be a big issue.
Having 25 Prefix implementations would just be plain wrong, but @dautelle or @desruisseaux what do you say?
The method is a convenience method, not half-implemented. Removing the enum corrected an old issue of having the US spelling by mistake. As early as JScience, where the US spelling was also used for METRE, so it produced an inconsistency we fixed with 2.2.

Seshat does not yet implement it, but I trust @desruisseaux will find a way to work with the new API, please clearly say, if that would suddenly be a problem.
After all, the US spelling is handled in resource bundles by Seshat with `cm=centimeter` for US and `cm=centimetre` for UK. 
There is currently no translation for things like `dag=decagram` (UK) vs. `dag=dekagram ` (US), but there is a mechanism for that if needed.
I know, it's a breaking change, but having to skip enums or break the API and TCK by being forced to change all JUnit tests plus the TCK (by changing `NUM_OF_METRIC_PREFIXES = 24` to 25) seems just plain wrong.
