### ISSUE TITLE
Clarify SystemOfUnit.getUnit(Class) behavior for unknown type

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#37]
`SystemOfUnit.getUnit(Class<Q> quantityType)` does not said what to do if no unit is found for the given quantity type. Should the method returns `null` or throw an exception?

Needs #65

**Comment by desruisseaux** [comment]
What was the decision for that one?

**Comment by keilw** [comment]
We specified that the actual `SystemOfUnits` is `null `if a wrong or non-existent name was passed to http://unitsofmeasurement.github.io/unit-api/site/apidocs/javax/measure/spi/SystemOfUnitsService.html. https://github.com/unitsofmeasurement/unit-api/issues/65 addresses the need to use a constant in the RI like GRAM, so you can do SystemOfUnits.getUnit("g") instead. This method uses a Lambda to filter the result, the method in question retrieves values from a Map, so if you pass a non-existent or non-defined quantity class, it returns `null`. As we even return `null` for the entire unit system since 1.0 it does not make sense to do something different for one method as for the others. 

It always returned null based on the call to Map, now the JavaDoc explains the behavior like it does in the other two cases (e.g. SystemOfUnitsService). It has been clarified, I don't think we should try to change the behavior, else we had to either deal with `Optional` or introduce new exceptions.
Like `NoSuchUnitException`, `UnitExistsException` or `UnitSystemException` in UCAR Units.
