### ISSUE TITLE
Java 9 support for other profiles

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/unit-api#42]
Based on https://github.com/unitsofmeasurement/unit-api/issues/41 the other profiles in https://github.com/unitsofmeasurement/unit-api/blob/master/pom.xml (to create smaller JARs according to profiles from the Spec) should also be able to expose a module like` java.measure.core` or similar to distinguish them from other modules.

At the moment these are subsets exposing the relevant packages only and we don't aim to make the "Full Profile" a collection of these modules (though Jigsaw technically would allow that)

**Comment by desruisseaux** [comment]
As said in previous discussion, I strongly object against splitting the 27 kb `unit-api-1.0.1-SNAPSHOT.jar` into a bunch of smaller files.

- The gain of disk space is insignificant even for a micro-devices. Quite the opposite, it takes more space if a devices want the full API.
- There is no gain in memory usage since the JVM loads only the required classes. Quite the opposite, it consumes more memory because of additional `java.lang.Module` to be created.
- It makes no difference in the separation of concerns since the packages already provide such separation. If one module contains many packages, modules is a nice way to group related tasks together. But if we have "1 module = 1 package", then those modules bring nothing.

Inconvenient is module path pollution. It makes the module path longer (forcing users to think about more elements) and increase the risk of incompatible version numbers between different parts of the API. This is likely to happen for example when using two libraries depending on different versions of JSR-363: we may have library A loading `java.measure.bla` version 1.0 and library B who depends on `java.measure.bla` version 1.1 (fictive), but does not load it because it was already loaded by library A, and adds a `java.measure.foo` version 1.1 to it.

So splitting JSR-363 API in many modules increase maintenance cost for all users for no advantage I can see.

**Comment by keilw** [comment]
Based on the modularity and optionality those who only need the smallest part of the API they shall be able to do that using dedicated modules. The "all" or "full" jar currently won't be split into those modules, thus there are separate modules like "java.measure.base" similar to the JDK. Those who need it ma use matching Maven profiles to build individual module jars.

**Comment by thodorisbais** [comment]
Shall we close this one, given the comment above?

**Comment by keilw** [comment]
No it's not done yet.

**Comment by keilw** [comment]
The `modules/core` folder should be called `modules/base`, it's historically the name of the "Core Profile" but "base" blends better with how the JDK calls its most basic module.

**Comment by desruisseaux** [comment]
I'm a little bit confused about those profiles stuff. Are we talking about Maven modules or Jigsaw modules? I'm neutral about Maven profiles or modules, as long as it is possible for projects like GeoAPI to depends on a single JAR file for the full API from Maven Central.

However for Jigsaw modules, I would still like a single module in a single JAR for full API. But if we provide both a "single module for all" and "many nano-modules", we will have conflicts if those two distributions appear together on the module path (the JVM will refuse to start).

So is it only about Maven profiles (I have no objection to that), or is it also about Jigsaw modules?

**Comment by keilw** [comment]
A bit of both. Jigsaw (based on how improved it for the "Full" module ;-) defines specific modules that are different from the "all" module, e.g. "java.measure.base". At the moment the "java.measure" module does not consume those, although in theory it might some day, but so far it is small enough to avoid it. The Maven part uses the same classifier as we do in a few other places (mostly extension modules or demos) for platform or JDK specific elements. Therefore you must use something different either way, the Maven cordinates are `unit-api-base` or similar, never just `unit-api`, and the Jigsaw modul is e.g. `java.measure.base`. Whoever wants to use them will in most cases need a small scale implementation, the RI at least is not meant to use it. We'll probably demonstrate it with a slightly modified branch of `https://github.com/unitsofmeasurement/uom-impl-enum`.  The important aspect is, those subsets of the API and small implementations can still pass the TCK in a particular profile like "Minimal" or "Format". Per definition the Java Module System only allows one package per module, so it makes no sense to declare "java.measure.quantity" and "java.measure.quantity.base" although we do have such profiles (they can be used without JPMS) This is mainly for Edge devices and we don't intend to put the Maven artifacts on MavenCentral at the moment.

**Comment by keilw** [comment]
https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html could be of help.

**Comment by keilw** [comment]
The "profile jar" profiles make little sense and they mix the base `module-info` with another `Automatic-Module-Name`, so they were disregarded. While it would be too cumbersome to create a module-info for any of the module JARs beside "base" we use `Automatic-Module-Name` and smaller applications can combine the modules they need.
