### ISSUE TITLE
Provide default method only it can fulfill the method contract

### ISSUE THREAD

**Issue by desruisseaux** [unitsofmeasurement/unit-api#76]
In Unit-API development branch, some default method implementations have been added in the interfaces. I suggest to do so only when the default implementation can fulfill the method contract. In particular:

* `UnitConverter.isIdentity()` should not return `false` by default. The method contract said that a value of `false` means that the unit converter is not identity. The default method can hardly detect that by itself.
* `UnitConverter.isLinear()` should not return `isIdentity()` by default. This would be okay only when this method returns `true`. In the vast majority of cases, this default method would return `false` because the converter is not the identity one, but it still linear.

Note that the above does not necessarily apply to `AbstractConverter` in the reference implementation. In that later case, the strategy to define those default methods in an abstract class is an implementation choice. Since the person who define `AbstractConverter` is the same that the one who define the concrete classes on top of it, we can presume that (s)he know what (s)he is doing. But in the Unit-API case, the group defining `UnitConverter` is not the same than the group who will implement it.

**Comment by keilw** [comment]
Well it's certainly a burden and overhead for every implementation if we leave that in `AbstractConverter`. Since the vast majority of implementations are locale-agnostic by design, `UnitFormat` or `QuantityFormat` also do this with `isLocaleSensitive()`. One could also argue only implementations know that, but if they do they `override` a default. For linear it may make a bit more sense to leave it to implementations, but how many implementing classes have `isIdentity()` returning `true` right now?

**Comment by desruisseaux** [comment]
It is true that very few implementations will have `isIdentity()` to return `true`, but it is not my issue. My issue is that the default implementation can not know what is the right answer.

Consider the following scenario: someone create a new `UnitConverter` implementation and implement only the abstract methods, because he get compiler errors if he doesn't. Since he got no compiler error for not overriding `isIdentity()`, he may forget to implement that method for its identity transform. This will result in a bug in his framework, which may be detected late.

It is not a hight burden for implementers to write `return false` in one place. Many will do exactly like the reference implementation did: write that once for ever in their own `AbstractConverter` class. By forcing implementers to do so, we force them to think about this question and take a decision about how they are going to handle it in their implementation.

**Comment by keilw** [comment]
But then why use it in `UnitFormat`? Someone who really implements UnitFormat or UnitConverter usually should know what they are doing, not rely on the compiler to tell them. Of course most modern IDEs allow that with a single click or less, if they want to do it "quick and dirty" without careful thinking this would also help them.

**Comment by desruisseaux** [comment]
We could consider avoiding default methods in `UnitFormat` too. My proposal is to provide default methods in Unit-API only when we can do that in a way that fulfill the contract - this is what JavaSE does with new methods in the collection framework. `AbstractConverter` in the reference implementation would be different because it is an implementation choice.

**Comment by keilw** [comment]
Unless we had something like the concept of `getDisplayName()` for `Unit`, `Quantity`, etc. (the funny thing is, there JSR 310 just returns return `toString()` as a `default` method) I would leave UnitFormat like it is. Other `boolean` methods in the rudimentary API of `java.time` (it will probably never see another implementation because the RI was baked into the API so an independent implementation without Oracle JDK is impossible) hint we might leave methods in `UnitConverter` non-default. Please propose a PR if you have time.

**Comment by keilw** [comment]
I think this is done via the PR.
